---
title: "SolasRworksheet#4b"
author: "Brian Kenneth Solas"
date: "2023-11-22"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1
vectorA <- c(1, 2, 3, 4, 5)
matrixA <-matrix(0, nrow = 5, ncol = 5)

matrixA

#    [,1] [,2] [,3] [,4] [,5]
#[1,]    0    0    0    0    0
#[2,]    0    0    0    0    0
#[3,]    0    0    0    0    0
#[4,]    0    0    0    0    0
#[5,]    0    0    0    0    0

for (i in 1:5) {
  for (j in 1:5) {
    matrixA[i , j] <- abs(vectorA[i] - vectorA[j])
  }
}

matrixA

#      [,1] [,2] [,3] [,4] [,5]
#[1,]    0    1    2    3    4
#[2,]    1    0    1    2    3
#[3,]    2    1    0    1    2
#[4,]    3    2    1    0    1
#[5,]    4    3    2    1    0
```
```{r}
#2
rightTriangle <- c()
for(i in 1:5) {
  for(j in 1:i+1) {
    rightTriangle = c(rightTriangle, "*")
  }
  print(rightTriangle)
  rightTriangle <- c()
}

#[1] "*"
#[1] "*" "*"
#[1] "*" "*" "*"
#[1] "*" "*" "*" "*"
#[1] "*" "*" "*" "*" "*"
```
```{r}
#3

n <- as.integer(readline(prompt = "Enter the number of terms: "))
#Enter the number of terms: 

a <- 0
b <- 1

cat("Fibonacci Sequence:", a, b)

#Fibonacci Sequence: 0 1

repeat {
  c <- a + b
  if(c > 500) {
    break
  }
  cat(", ",c)
  a <- b
  b <- c
}

#,  1,  2,  3,  5,  8,  13,  21,  34,  55,  89,  144,  233,  377
```
```{r}
#4
#A
HouseholdData <- read.table("HouseholdData.csv",header = TRUE, sep = ",", as.is = TRUE)


head(HouseholdData,6)

#  X shoe_size height
#1 1       6.5   66.0
#2 2       9.0   68.0
#3 3       8.5   64.5
#4 4       8.5   65.0
#5 5      10.5   70.0
#6 6       7.0   64.0

#B

male_subset <- subset(HouseholdData, Gender == 'M')
female_subset <- subset(HouseholdData, Gender == 'F')

male_count <- nrow(male_subset)
male_count

#[1] 14

female_count <- nrow(female_subset)
female_count

#[1] 14

#c

count <- c(male_count, female_count)
Gender <- c("Male", "Female")

barplot(count,
        names.arg = Gender,
        main = "The number of Males and Females in Household Data",
        xlab = "Gender",
        ylab = "Count",
        col = c("blue", "pink"))
legend("topright",
       legend = Gender,
       fill = c("blue", "pink"))
```
```{r}
#5
#A
monthly_income <- c(60,10,5,25)

month_labels <- round(monthly_income/sum(monthly_income)*100,1)
month_labels <- paste(month_labels,"%", sep = "")

pie(monthly_income, main = "The monthly income of Dele Cruz Family",
    col= rainbow(length(monthly_income)),
    labels = month_labels,
    cex = 0.8)

legend(1.5,0.5,
       c("Food", "Electricity","Savings","Miscellaneous"),
       fill = rainbow(length(monthly_income)))
```
```{r}
#6
#a
data(iris)

str(iris)

```
```{r}
#b
mean<- colMeans(iris[, c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")])
mean
```
```{r}
#C
pie(table(iris$Species),
    main = "Species Distribution",
    labels = levels(iris$Species),
    col = c("lightblue","lightgreen","red"))
legend("topright", legend = levels(iris$Species), 
       fill = c("lightblue", "lightgreen", "red"),
       title = "Setosa","Versicolor","Virginica")
```
```{r}
#D
setosa_lastsix<-tail(subset(iris, Species == "setosa"), n = 6)
versicolor_lastsix<-tail(subset(iris, Species == "versicolor"), n = 6)
virginica_lastsix<-tail(subset(iris, Species == "virginica"), n = 6)
setosa_lastsix
```
```{r}
versicolor_lastsix
```
```{r}
virginica_lastsix
```

```{r}
#E
plot(iris$Sepal.Length, iris$Sepal.Width,
     pch = as.integer(iris$Species),
     col = as.integer(iris$Species) + 1,
     main = "Iris Dataset",
     sub = "Sepal width and length",
     xlab = "Sepal length",
     ylab = "Sepal width",
     cex = 1.5,
     lwd = 1.5)
```

```{r}
as.factor(iris$Species)
```

```{r}
#7
#A
library(readr)
library(readxl)
alexa_file <- read_excel("/cloud/project/alexa_file.xlsx")
#View(alexa_file)

alexaVariation <- gsub("Black Plus", "Black Plus", alexa_file$variation)
alexa_file$variation <- gsub("Black Show", "Black Show", alexa_file$variation)
alexa_file$variation <- gsub("Black Spot", "Black Spot", alexa_file$variation)
alexa_file$variation <- gsub("Black Dot", "Black Dot", alexa_file$variation)
alexa_file$variation <- gsub("White Dot", "White Dot", alexa_file$variation)
alexa_file$variation <- gsub("White Plus", "White Plus", alexa_file$variation)
alexa_file$variation <- gsub("White Spot", "White Spot", alexa_file$variation)
alexa_file$variation <- gsub("White Show", "White Show", alexa_file$variation)

```

```{r}
#B
library(dplyr)

#Attaching package: ‘dplyr’
#
#The following objects are masked from ‘package:stats’:
#
#    filter, lag
#
#The following objects are masked from ‘package:base’:
#
#    intersect, setdiff, setequal, union

save(alexa_file, file = "variations.RData")
load("variations.RData")
alexaVariation <- alexa_file%>%count(alexa_file$variation)
alexaVariation
```

```{r}
#C
barplot(
height = alexaVariation$n,
names.arg = alexaVariation$`alexa_file$variation`,
col = "pink",
main = "Alexa Varations",
las = 2,
cex.names = 0.58
)

```


```{r}
par(mfrow = c(1, 2))
black_variants <- alexaVariation[1:5,]
white_variants <- alexaVariation[12:16,]
barplot(
height = black_variants$n,
names.arg = black_variants$`alexa_file$variation`,
main = "Black Variants",
col = rainbow(8),
xlab = 'Total Numbers',
ylab = 'Frequency',
cex.names = 0.35,
)
barplot(
height = white_variants$n,
names.arg = white_variants$`alexa_file$variation`,
main = "White Variants",
col = rainbow(8),
xlab = 'Total Numbers',
ylab = 'Frequency',
cex.names = 0.35,
)
```

